# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"\"\n\x0eWeatherRequest\x12\x10\n\x08location\x18\x01 \x01(\t\"K\n\x0fWeatherResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x11\n\tcondition\x18\x03 \x01(\t2X\n\x0eWeatherService\x12\x46\n\x11GetCurrentWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERREQUEST']._serialized_start=26
  _globals['_WEATHERREQUEST']._serialized_end=60
  _globals['_WEATHERRESPONSE']._serialized_start=62
  _globals['_WEATHERRESPONSE']._serialized_end=137
  _globals['_WEATHERSERVICE']._serialized_start=139
  _globals['_WEATHERSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
